STATALL version 0.2

diff --git a/bin/STATALL b/bin/STATALL
--- a/bin/STATALL
+++ b/bin/STATALL
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+
+echo "STATALL, Version 0.2"
+echo "Use: 'STATALL --help' for some infos."
+sleep 1
+
 function usage {
   echo -e "Usage: $(basename $0) \e[36m [gc|get|br|--source for@bar]\e[0m \n"
   echo ""
@@ -8,7 +13,7 @@ function usage {
   echo ""
   echo "* Check localy:"
   echo "   gc  = run garbagecollector"
-  echo "   get = git pull origin master"
+  echo "   get = git pull <remote> master"
   echo "   br  = show branches"
   echo ""
   # echo "$(basename $0) checks only .git - directories."
@@ -43,10 +48,15 @@ if [[ "$1" == "--help" || "$1" == "-?" ]]; then
   exit 1
 fi
 
+#######################################################################
+#
+# MAIN LOOP
+#
+#######################################################################
 C=0
 for n in $(ls -d */); do
   C=$(expr $C + 1)
-  echo -e "\n $C # Checking \e[1;36m$n\e[0m (master) ... "
+  echo -e "\n[$C] # Checking \e[1;36m$n\e[0m (master) ... "
   cd $n
 
   if [[ ! -d ".git" ]]; then
@@ -55,50 +65,58 @@ for n in $(ls -d */); do
     continue
   fi
 
-  echo -e "Checking out master ... "
-  git checkout master 2> /dev/null
-  git fetch -p
-  # if [ "$1" == "b" ]; then echo -e "\n\e[33mBRANCHES:\e[0m\n"; git branch -av; echo -e "\t\t\t\t\tSTATE: \c"; fi
 
-  git status | grep clean
-  if [ $? -ne 0 ]; then
-    #echo -e "\t_________________________________"
-    echo -e "\t\t\t\t\t\t\t \e[1;31mChanges open\e[0m"
-    git status | grep modif
-    #echo -e "\t_________________________________"
-    changesOpen="${changesOpen} $n"
-    #exit 1
-  else
-    echo -e "\t\t\t\t\t\t\t \e[1;32mOK\e[0m"
-    if [[ "$1" == "gc" ]]; then
-      echo -e " \e[1;21m>performing a gc:\e[0m"
-      git gc
-      echo -e " \e[1;21m>performing a fsck:\e[0m"
-      git fsck
-    elif [[ "$1" == "get" ]]; then
-      git pull origin master 2> /dev/null
-      if [ $? -ne 0 ]; then
-        echo -e "\t\t\e[41mPULL NOT POSSIBLE! \e[0m"
+
+
+  for remote in $(git remote)
+  do
+    echo -e "\n\e[1;34mUsing remote: \e[0m: $(git remote -v |grep $remote)"
+    echo -e "Checking out master ... "
+    git checkout master 2> /dev/null
+    # git fetch --all -p
+    # if [ "$1" == "b" ]; then echo -e "\n\e[33mBRANCHES:\e[0m\n"; git branch -av; echo -e "\t\t\t\t\tSTATE: \c"; fi
+
+    git status | grep clean
+    if [ $? -ne 0 ]; then
+      #echo -e "\t_________________________________"
+      echo -e "\e[1;31mChanges open\e[0m , please commit them first!"
+      git status | grep modif
+      #echo -e "_________________________________"
+      changesOpen="${changesOpen} $n"
+      exit 1
+    else
+      echo -e "\t\t\t\t\t\t\t \e[1;32mOK\e[0m"
+      if [[ "$1" == "gc" ]]; then
+        echo -e " \e[1;21m>performing a gc:\e[0m"
+        git gc
+        echo -e " \e[1;21m>performing a fsck:\e[0m"
+        git fsck
+      elif [[ "$1" == "get" ]]; then
+        echo -e "trying to pull ..."
+        git pull ${remote} master 2> /dev/null
+        if [ $? -ne 0 ]; then
+        echo -e "\e[43mpull failed! \e[0m"
+        fi
+      fi
+
+      to_push=$(git status | grep -E 'git push')
+      if [[ ! -z $to_push ]]; then
+        echo -e "\e[43mYou can push some changes. =) \e[0m"
+        reposToPush="${reposToPush} $n"
+      fi
+      to_pull=$(git status | grep -E 'git pull')
+      if [[ ! -z $to_pull ]]; then
+        echo -e "\e[44mYou can pull some changes. =) \e[0m"
+      fi
+
+      if [[ "$1" == "br" ]]; then
+        echo "branches _without_ master:"
+        echo -e "\e[1;35m"
+        git branch -a | grep -v master
+        echo -e "\e[0m"
       fi
     fi
-
-    to_push=$(git status | grep -E 'git push')
-    if [[ ! -z $to_push ]]; then
-      echo -e "\t\t\t\t\e[43mYOU HAVE TO PUSH SOME CHANGES. =) \e[0m"
-      reposToPush="${reposToPush} $n"
-    fi
-    to_pull=$(git status | grep -E 'git pull')
-    if [[ ! -z $to_pull ]]; then
-      echo -e "\t\t\t\t\e[44mYOU CAN PULL SOME CHANGES. =) \e[0m"
-    fi
-
-    if [[ "$1" == "br" ]]; then
-      echo "branches _without_ master:"
-      echo -e "\e[1;35m"
-      git branch -a | grep -v master
-      echo -e "\e[0m"
-    fi
-  fi
+  done
 
   #YOUR=$(git status | grep -i your | wc -l)
   #if [ $YOUR -ne 0 ]; then
