bashrc: added stuff from dot-profile

diff --git a/profile/bashrc b/profile/bashrc
--- a/profile/bashrc
+++ b/profile/bashrc
@@ -2,6 +2,72 @@
 # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
 # for examples
 
+. /etc/bash_completion.d/git-prompt || fail "Cannot source /etc/bash_completion.d/git-prompt"
+
+
+#cd () {
+#  builtin cd "$@"
+#  ls IMPORTANT* >/dev/null 2>&1 && echo -e "\e[31mImportant File found.\e[0m"
+#  ls README* >/dev/null 2>&1 && echo -e "\e[32mReadme File found.\e[0m"
+#}
+
+if [ -s "$MAIL" ]           # This is at Shell startup.  In normal
+then
+    echo "$MAILMSG"        # operation, the Shell checks periodically.
+fi
+
+PATH=$PATH:.:~/bin/
+export JAVA_HOME="~/bin/java/jre1.8.0_211"
+export GEM_HOME="$HOME/.gems"
+export GEM_PATH="$HOME/.gem"
+
+alias ls='ls --color=auto'
+alias l='ls '
+alias ll='ls -l'
+alias la='ls -a'
+alias ltr='ls -ltr'
+alias mv='mv -i'
+alias rm='rm -v'
+alias n='nslookup'
+alias s='sudo su -'
+alias lxterminal='lxterminal --geometry=100x57'
+alias showrgb='showrgb | less'
+
+#
+# git aliases ################################################################
+#
+alias fetch='git fetch -v'
+alias gitone='git log --pretty=oneline'
+alias gitoneline='gitone'
+alias gitpretty='gitone'
+alias gitlast='git diff HEAD^..HEAD'
+alias gitlog='git log -p'
+alias gitlogsum='git log --stat --summary'
+alias stat='git status ; git stash list'
+alias gitime="git log --pretty=format:'%h was %an, %ar, message: %s'"
+alias gd="git diff"
+alias gdc="git diff --cached"
+alias changelog='git log > changelog'
+alias gb='git branch -a'
+
+#
+# editors
+#
+alias np='gedit'
+alias gy='geany'
+alias sub='~/bin/sublime_text/sublime_text'
+
+#
+# we try this out ...
+#
+# source ~/liquidprompt/liquidprompt
+
+#
+# PS1 ########################################################################
+#
+export PS1='\[\033[01;32m\]\u@\h\[\033[01;35m\] \w\[\033[01;33m\]\[\033[01;35m\]$(__git_ps1) \$\[\033[00m\] '
+
+
 # If not running interactively, don't do anything
 case $- in
     *i*) ;;
@@ -182,7 +248,6 @@ export SCM_CHECK=true
 
 # Uncomment this to make Bash-it create alias reload.
 # export BASH_IT_RELOAD_LEGACY=1
-export GEM_HOME="$HOME/.gems"
 
 # Load Bash It
 source "$BASH_IT"/bash_it.sh
